# appveyor.yml
---
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install tox"

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
